import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import React from 'react';

import { MainNav } from '../components/main-nav';
import MobileNav from '../components/mobile-nav';
import { SiteFooter } from '../components/site-footer';
import { ModeToggle } from '../components/toggle';
import { buttonVariants } from '../components/ui/button';
import { cn } from '../utils/micelane';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function NetflixDashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex min-h-screen flex-col overflow-hidden pb-10">
        <header className="h-16 container px-5 sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="flex h-16 items-center justify-between py-6 w-full">
            <MobileNav />
            <MainNav />
            <nav>
              <div className="md:flex">
                <div className="flex gap-4">
                  <ModeToggle />
                </div>
              </div>
            </nav>
          </div>
        </header>
        <main className="flex-1 overflow-hidden">{children}</main>
      </div>

      <SiteFooter />
    </>
  );
}
